### ISSUE TITLE
No tenant support here when authentication and token request without user?

### ISSUE THREAD

**Issue by cnc0090306** [GearPlug/microsoftgraph-python#19]
Just as the title describes

**Comment by cnc0090306** [comment]
token request without users
https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0

there is no refresh_token in response and also redirect_uri is not required here

**Comment by ingmferrer** [comment]
Hello, at this time the library does not support access without users. Sorry.
