### ISSUE TITLE
Flow for signing in user and getting "code"

### ISSUE THREAD

**Issue by leinad9905** [GearPlug/microsoftgraph-python#38]
Hey there, with this flow, what step do you recommend to pass "code" to exchange code for access token. I understand the user would login in the browser. Sorry if the question is low level, still learning more about Graph API

**Comment by cormac-everhaze** [comment]
When the user visits the url that comes from `url = client.authorization_url(redirect_uri, scope, state=None)`, you should see the key "code" is passed to your callaback view.

Then just pass the code value into `client.exchange_code(redirect_uri, code)` and you will get an access token for that user.

**Comment by tonnyhideyori** [comment]
I put scope OpenID, I just receive the encoded URL, and I have not seen any code. can you please provide a parameter to access this code

**Comment by ingmferrer** [comment]
Sorry for the late response.

You should be able to access it with `.data` property.
