### ISSUE TITLE
KeyError when passing folder_id param to Mail().list_messages()

### ISSUE THREAD

**Issue by cormac-everhaze** [GearPlug/microsoftgraph-python#39]
In the file mail.py:

line 32 `url = "me/mailFolders/{id}/messages".format(folder_id) if folder_id else "me/messages"`

should be

`url = "me/mailFolders/{id}/messages".format(id=folder_id) if folder_id else "me/messages"`

or better again use f-strings!

**Comment by ingmferrer** [comment]
Hello, sorry for the late response.

This should be fixed now.

Thanks!
