### ISSUE TITLE
Incorrect AUTHORITY_URL

### ISSUE THREAD

**Issue by jkmartindale** [GearPlug/microsoftgraph-python#5]
For some reason `AUTHORITY_URL` and `OFFICE365_AUTHORITY_URL` are switched, so that the behavior of the `office365` parameter to `Client`'s constructor is the opposite of the expected behavior.

**Comment by ingmferrer** [comment]
Seems like you're right but I need to test it before making any change.

If you would like to submit a PR, it would be nice.

**Comment by dhirajpatil19** [comment]
instead of switching url i tried office365=False and got following error - 
Specified tenant identifier 'by defect common' is neither a valid DNS name, nor a valid external domain.
please help.

**Comment by jkmartindale** [comment]
> Specified tenant identifier 'by defect common' is neither a valid DNS name, nor a valid external domain.

Your problem isn't related to this issue at all.

`account_type` for the Client object corresponds to the `tenant` GET variable for the API's [authorization flow](https://docs.microsoft.com/en-us/graph/auth-v2-user). Valid values include "common", "organizations", and "consumers", among other things. "by defect common" isn't a valid value.

This library defaults to "common", which will work for all personal Microsoft accounts and organization Office 365 accounts. So unless you need to restrict who can use the application, you don't need to specify the `account_type` variable when constructing Client.
